name: Pull strings from transifex

on:
  schedule:
    # 7:45 every day
    - cron:  '45 7 * * *'
  push:
    branches:
      - main

# Allow one concurrent deployment
concurrency:
  group: "tx_pull"
  cancel-in-progress: true

jobs:
  update:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install deps
        run: |
          pip install transifex-client

      - name: Create .tx/config
        run: |
          mkdir -p .tx
          curl https://raw.githubusercontent.com/qgis/QGIS-Website/master/.tx/config -o .tx/config

      - name: Pull translations
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}
        run: |
          tx pull -a -f

      - name: Push repository
        run: |
          git config --global user.name 'Transifex update'
          git config --global user.email 'tx-update@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git status
          git add .
          git commit -m "Automated update"
          git push
